config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    get '/' => 'users#dashboard'

    resources :users do
      collection do
        get :dashboard
      end
    end

    resources :sessions do
      collection do
        get :login
        post :login_attempt
        get :logout
      end
    end

    resources :roles
    resources :permissions
    resources :parties
    resources :colors
    resources :types
    resources :plastic_scraps
    resources :fillers
    resources :bobins
    resources :gittis
    resources :tapes
    resources :thellies
    resources :daanas

  end
end

app/models/filler.rb
class Filler < ApplicationRecord
  belongs_to :party
  belongs_to :color
end

app/controllers/admin/fillers_controller.rb
class Admin::FillersController < ApiController
  before_action :authenticate_user

  def index
    @q = Filler.ransack(params[:q])
    @fillers = @q.result.paginate(page: params[:page], per_page: 10)
  end

  def new
    @filler = Filler.new
  end

  def create
    @filler = Filler.new(filler_params)
    if @filler.save
      set_flash_notification :success, :create, entity: 'Filler'
      redirect_to admin_fillers_path
    else
      set_instant_flash_notification :danger, :default, {:message => @filler.errors.messages[:base][0]}
      render :new
    end
  end

  def edit
    @filler = Filler.find(params[:id])
  end

  def update
    @filler = Filler.find(params[:id])
    if @filler.update(filler_params)
      set_flash_notification :success, :update, entity: 'Filler'
      redirect_to admin_fillers_path
    else
      set_instant_flash_notification :danger, :default, {:message => @filler.errors.messages[:base][0]}
      render :edit
    end
  end

  def destroy
    @bobin = Filler.find(params[:id])
    @bobin.delete
    redirect_to admin_fillers_path
  end

  def upload_filler_image
    UploadToS3Service.new(params[:document], params[:id], {extension: 'jpg', public_read: true, upload_folder: "fillers"}).update_file
    set_flash_notification :success, :update, entity: 'Filler'
    redirect_to admin_fillers_path
  end

  private

  def filler_params
    params.require(:filler).permit(:party_id, :color_id, :quantity, :rate)
  end
end

app/views/admin/fillers/edit.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <u><h2>Fillers</h2></u>
    </div>
    <div class="col-xs-12">
      <div class="col-md-2 col-md-offset-2">
        <h3>
          <%= link_to admin_fillers_path, class: "btn btn-blue" do %>
            Back
          <% end %>
        </h3>
      </div>
    </div>
  </div>

  <div class="col-xs-8 col-xs-offset-2">
    <table class="table table-bordered table-striped table-hover table-data table-overview display" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-3">Party</th>
        <th class="col-xs-2">Color</th>
        <th class="col-xs-1">Quantity</th>
        <th class="col-xs-1">Rate</th>
        <th class="col-xs-2">Date</th>
        <th class="col-xs-2">Action</th>
      </tr>
      </thead>
      <tbody>
      <% Filler.all.each do |filler| %>
        <tr>
          <td><%= filler.id%></td>
          <%if filler.id == @filler.id %>
            <%= form_for @filler, url: admin_filler_path do |f| %>
              <td><%= f.select :party_id, Party.all.pluck(:name, :id), {include_blank: "--Party--"},
                               { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select", required: true}%></td>
              <td><%= f.select :color_id, Color.all.pluck(:name, :id), {include_blank: "--Color--"},
                               { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select", required: true}%></td>
              <td><%= f.text_field :quantity, class: 'form-control input feedr-main-input', required: true %></td>
              <td><%= f.text_field :rate, class: 'form-control input feedr-main-input', required: true %></td>
              <td><%= filler.created_at.strftime("%d/%m/%Y")%></td>
              <td>
                <%= f.submit "Update", class: 'btn btn-green' %>
              </td>
            <% end %>
          <% else %>
            <td><%= Party.find_by(:id => filler.party_id).name %></td>
            <td><%= Color.find_by(:id => filler.color_id).name %></td>
            <td><%= filler.quantity%></td>
            <td><%= filler.rate%></td>
            <td><%= filler.created_at.strftime("%d/%m/%Y")%></td>
            <td>
            </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%#= will_paginate @locations%>
    </div>
  </div>
</div>

app/views/admin/fillers/index.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <u><h2>Fillers</h2></u>
    </div>
    <div class="col-xs-12 no-left-pad">
      <div class="col-md-2 col-md-offset-2 ">
        <h3>
          <%= link_to new_admin_filler_path, class: "btn btn-green" do %>
            Add New Filler
          <% end %>
        </h3>
      </div>
    </div>
  </div>

  <div class="col-xs-8 col-xs-offset-2">
    <%= search_form_for(@q,url: admin_fillers_path, id: 'fillers_search_form') do |f| %>

      <div class="col-xs-2 pt20">

        <%=f.select :party_id_eq, Party.all.pluck(:name, :id), {include_blank: "--Party--"},
                    { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select"}%>
      </div>

      <div class="col-xs-2 pt20">

        <%=f.select :color_id_eq, Color.all.pluck(:name, :id), {include_blank: "--Color--"},
                    { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select"}%>
      </div>

      <div class="col-xs-2 pt20" align="right">
        <%=f.submit 'Search', class: 'form-control btn-green'%>
      </div>
    <%end%>
  </div>

  <div class="col-xs-8 col-xs-offset-2 top-margin-3">
    <table class="table table-bordered table-striped feedr-main-tabl" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-3">Party</th>
        <th class="col-xs-2">Color</th>
        <th class="col-xs-1">Quantity</th>
        <th class="col-xs-1">Rate</th>
        <th class="col-xs-2">Date</th>
        <th class="col-xs-2">Action</th>
      </tr>
      </thead>
      <tbody>
      <% @fillers.each do |filler| %>
        <tr>
          <td><%= filler.id%></td>
          <td><%= Party.find_by(:id => filler.party_id).name %></td>
          <td><%= Color.find_by(:id => filler.color_id).name %></td>
          <td><%= filler.quantity%></td>
          <td><%= filler.rate%></td>
          <td><%= filler.created_at.strftime("%d/%m/%Y")%></td>
          <td>
            <div>
              <div class="col-xs-4">
                <%= link_to edit_admin_filler_path(filler), class: "btn btn-primary" do %>
                  Edit
                <% end %>
              </div>
              <div class="col-xs-4">
                <%= link_to 'Delete', admin_filler_path(filler), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>

              </div>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%= will_paginate @fillers%>
    </div>
  </div>
</div>

<script>
    $('#document').change(function(){
        $('#upload_form').submit()
    });
</script>

app/views/admin/fillers/new.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <u><h2>Fillers</h2></u>
    </div>
    <div class="col-xs-12 no-left-pad">
      <div class="col-md-2 col-md-offset-2">
        <h3>
          <%= link_to admin_fillers_path, class: "btn btn-blue" do %>
             Back
          <% end %>
        </h3>
      </div>
    </div>
  </div>

  <div class="col-xs-8 col-xs-offset-2">
    <table class="table table-bordered table-striped" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-3">Party</th>
        <th class="col-xs-2">Color</th>
        <th class="col-xs-1">Quantity</th>
        <th class="col-xs-1">Rate</th>
        <th class="col-xs-2">Date</th>
        <th class="col-xs-2">Action</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td></td>
        <%= form_for @filler, url: admin_fillers_path do |f| %>
          <td><%= f.select :party_id, Party.all.pluck(:name, :id), {include_blank: "--Party--"},
                           { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select", required: true}%></td>
          <td><%= f.select :color_id, Color.all.pluck(:name, :id), {include_blank: "--Color--"},
                           { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select", required: true}%></td>
          <td><%= f.text_field :quantity, class: 'form-control input feedr-main-input', required: true %></td>
          <td><%= f.text_field :rate, class: 'form-control input feedr-main-input', required: true %></td>
          <td></td>
          <td>
            <%= f.submit "Save", class: 'btn btn-green' %>
          </td>
        <% end %>
      </tr>
      <% Filler.all.each do |filler| %>
        <tr>
          <td><%= filler.id%></td>
          <td><%= Party.find_by(:id => filler.party_id).name %></td>
          <td><%= Color.find_by(:id => filler.color_id).name %></td>
          <td><%= filler.quantity%></td>
          <td><%= filler.rate%></td>
          <td><%= filler.created_at.strftime("%d/%m/%Y")%></td>
          <td>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%#= will_paginate @locations%>
    </div>
  </div>
</div>