config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    get '/' => 'users#dashboard'

    resources :users do
      collection do
        get :dashboard
      end
    end

    resources :sessions do
      collection do
        get :login
        post :login_attempt
        get :logout
      end
    end

    resources :roles
    resources :permissions
    resources :parties
    resources :colors
    resources :types
    resources :plastic_scraps
    resources :fillers
    resources :bobins
    resources :gittis
    resources :tapes
    resources :thellies
    resources :daanas

  end
end

app/models/bobin.rb
class Bobin < ApplicationRecord
  belongs_to :party
end

app/controllers/admin/bobins_controller.rb
class Admin::BobinsController < ApiController
  before_action :authenticate_user

  def index
    @q = Bobin.ransack(params[:q])
    @bobins = @q.result.paginate(page: params[:page], per_page: 10)
  end

  def new
    @bobin = Bobin.new
  end

  def create
    @bobin = Bobin.new(bobin_params)
    if @bobin.save
      set_flash_notification :success, :create, entity: 'Bobin'
      redirect_to admin_bobins_path
    else
      set_instant_flash_notification :danger, :default, {:message => @bobin.errors.messages[:base][0]}
      render :new
    end
  end

  def edit
    @bobin = Bobin.find(params[:id])
  end

  def update
    @bobin = Bobin.find(params[:id])
    if @bobin.update(bobin_params)
      set_flash_notification :success, :update, entity: 'Bobin'
      redirect_to admin_bobins_path
    else
      set_instant_flash_notification :danger, :default, {:message => @bobin.errors.messages[:base][0]}
      render :edit
    end
  end

  def destroy
    @bobin = Bobin.find(params[:id])
    @bobin.delete
    redirect_to admin_bobins_path
  end

  def upload_bobin_image
    UploadToS3Service.new(params[:document], params[:id], {extension: 'jpg', public_read: true, upload_folder: "bobins"}).update_file
    set_flash_notification :success, :update, entity: 'Bobin'
    redirect_to admin_bobins_path
  end

  private

  def bobin_params
    params.require(:bobin).permit(:party_id, :quantity, :rate)
  end
end

app/views/admin/bobins/edit.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <u><h2>Bobins</h2></u>
    </div>
    <div class="col-xs-12">
      <div class="col-md-2 col-md-offset-2">
        <h3>
          <%= link_to admin_bobins_path, class: "btn btn-blue" do %>
            Back
          <% end %>
        </h3>
      </div>
    </div>
  </div>

  <div class="col-xs-8 col-xs-offset-2">
    <table class="table table-bordered table-striped table-hover table-data table-overview display" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-3">Party</th>
        <th class="col-xs-2">Quantity</th>
        <th class="col-xs-2">Rate</th>
        <th class="col-xs-2">Date</th>
        <th class="col-xs-2">Action</th>
      </tr>
      </thead>
      <tbody>
      <% Bobin.all.each do |bobin| %>
        <tr>
          <td><%= bobin.id%></td>
          <%if bobin.id == @bobin.id %>
            <%= form_for @bobin, url: admin_bobin_path do |f| %>
              <td><%= f.select :party_id, Party.all.pluck(:name, :id), {include_blank: "--Party--"},
                               { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select", required: true}%></td>
              <td><%= f.text_field :quantity, class: 'form-control input feedr-main-input', required: true %></td>
              <td><%= f.text_field :rate, class: 'form-control input feedr-main-input', required: true %></td>
              <td><%= bobin.created_at.strftime("%d/%m/%Y")%></td>
              <td>
                <%= f.submit "Update", class: 'btn btn-green' %>
              </td>
            <% end %>
          <% else %>
            <td><%= Party.find_by(:id => bobin.party_id).name %></td>
            <td><%= bobin.quantity%></td>
            <td><%= bobin.rate%></td>
            <td><%= bobin.created_at.strftime("%d/%m/%Y")%></td>
            <td>
            </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%#= will_paginate @bobin%>
    </div>
  </div>
</div>

app/views/admin/bobins/index.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <u><h2>Bobins</h2></u>
    </div>
    <div class="col-xs-12 no-left-pad">
      <div class="col-md-2 col-md-offset-2 ">
        <h3>
          <%= link_to new_admin_bobin_path, class: "btn btn-green" do %>
            Add Bobin
          <% end %>
        </h3>
      </div>
    </div>
  </div>


  <div class="col-xs-8 col-xs-offset-2">
    <%= search_form_for(@q,url: admin_bobins_path, id: 'bobin_search_form') do |f| %>

      <div class="col-xs-5 pt20">

        <%=f.select :party_id_eq, Party.all.pluck(:name, :id), {include_blank: "--Party--"},
                    { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select"}%>
      </div>
      <div class="col-xs-2 pt20" align="right">
        <%=f.submit 'Search', class: 'form-control btn-green'%>
      </div>
    <%end%>
  </div>

  <div class="col-xs-8 col-xs-offset-2 top-margin-3">
    <table class="table table-bordered table-striped feedr-main-tabl" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-3">Party</th>
        <th class="col-xs-2">Quantity</th>
        <th class="col-xs-2">Rate</th>
        <th class="col-xs-2">Date</th>
        <th class="col-xs-2">Action</th>
      </tr>
      </thead>
      <tbody>
      <% @bobins.each do |bobin| %>
        <tr>
          <td><%= bobin.id%></td>
          <td><%= Party.find_by(:id => bobin.party_id).name %></td>
          <td><%= bobin.quantity%></td>
          <td><%= bobin.rate%></td>
          <td><%= bobin.created_at.strftime("%d/%m/%Y")%></td>
          <td>
            <div>
              <div class="col-xs-4">
                <%= link_to edit_admin_bobin_path(bobin), class: "btn btn-primary" do %>
                  Edit
                <% end %>
              </div>
              <div class="col-xs-4">
                <%= link_to 'Delete', admin_bobin_path(bobin), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>

              </div>

            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%= will_paginate @bobins%>
    </div>
  </div>
</div>

<script>
    $('#document').change(function(){
        $('#upload_form').submit()
    });
</script>

app/views/admin/bobins/new.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <u><h2>Bobins</h2></u>
    </div>
    <div class="col-xs-12 no-left-pad">
      <div class="col-md-2 col-md-offset-2">
        <h3>
          <%= link_to admin_bobins_path, class: "btn btn-blue" do %>
             Back
          <% end %>
        </h3>
      </div>
    </div>
  </div>

  <div class="col-xs-8 col-xs-offset-2">
    <table class="table table-bordered table-striped" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-3">Party</th>
        <th class="col-xs-2">Quantity</th>
        <th class="col-xs-2">Rate</th>
        <th class="col-xs-2">Date</th>
        <th class="col-xs-2">Action</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td></td>
        <%= form_for @bobin, url: admin_bobins_path do |f| %>
          <td><%= f.select :party_id, Party.all.pluck(:name, :id), {include_blank: "--Party--"},
                           { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select", required: true}%></td>
          <td><%= f.text_field :quantity, class: 'form-control input feedr-main-input', required: true %></td>
          <td><%= f.text_field :rate, class: 'form-control input feedr-main-input', required: true %></td>
          <td></td>
          <td>
            <%= f.submit "Save", class: 'btn btn-green' %>
          </td>
        <% end %>
      </tr>
      <% Bobin.all.each do |bobin| %>
        <tr>
          <td><%= bobin.id%></td>
          <td><%= Party.find_by(:id => bobin.party_id).name %></td>
          <td><%= bobin.quantity%></td>
          <td><%= bobin.rate%></td>
          <td><%= bobin.created_at.strftime("%d/%m/%Y")%></td>
          <td>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%#= will_paginate @bobin%>
    </div>
  </div>
</div>