config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    get '/' => 'users#dashboard'

    resources :users do
      collection do
        get :dashboard
      end
    end

    resources :sessions do
      collection do
        get :login
        post :login_attempt
        get :logout
      end
    end

    resources :roles
    resources :permissions
    resources :parties
    resources :colors
    resources :types
    resources :plastic_scraps
    resources :fillers
    resources :bobins
    resources :gittis
    resources :tapes
    resources :thellies
    resources :daanas

  end
end

app/models/role.rb
class Role < ApplicationRecord

  # Associations
  has_many :user_roles, dependent: :restrict_with_exception
  has_many :users, through: :user_roles

  has_many :permission_roles, dependent: :restrict_with_exception
  has_many :permissions, through: :permission_roles

  # Accepts Nested Attributes
  accepts_nested_attributes_for :permissions

  # Validations
  validates :name, :description, presence: true
  validates :name, uniqueness: { case_sensitive: false, allow_blank: true }

  #scopes
  scope :active, -> { where(active: true) }
  scope :admin_only, -> { where(admin_only: true) }

end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < ApiController
  # # Filters
  before_action :authenticate_user
  before_action :only_allow_super_admin
  before_action :set_resource, only: [ :update, :edit]

  def index
    @roles = Role.all.paginate(page: params[:page])
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(permitted_params)

    if @role.save
      set_flash_notification :success, :create, entity: 'Role'
      redirect_to admin_roles_path
    else
      set_instant_flash_notification :danger, :default
      render :new
    end
  end

  def edit
  end

  def update
    if @role.update(permitted_params)
      set_flash_notification :success, :update, entity: 'Role'
      redirect_to admin_roles_path
    else
      set_instant_flash_notification :danger, :default
      render :edit
    end
  end

  private
    def permitted_params
      params.require(:role).permit(:name, :description, :active, :admin_only, permission_ids: [])
    end
end

app/helpers/roles_helper.rb
module RolesHelper
  def permissions_for_select
    Permission.pluck(:name, :id).to_a
  end

  def roles_for_select
    Role.pluck(:name, :id).to_a
  end
end

app/views/admin/roles/_form.html.erb
<div class="form-group col-md-6">
  <%= f.label :name, 'Name' %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group col-md-6">
  <%= f.label :description, 'Description' %>
  <%= f.text_area :description, class: 'form-control' %>
</div>

<div class="form-group col-md-12">
  <%= f.label :permission_ids, 'Permissions' %>
  <%= f.select :permission_ids, permissions_for_select, {}, class: 'form-control', 'data-behavior' => "chosen-select",  multiple: true %>
</div>

<%= javascript_include_tag 'roles/form' %>

app/views/admin/roles/edit.html.erb
<div class="container col-md-8 col-md-offset-2">
  <div class="row">
    <h4 class="col-md-2">
      <%= link_to admin_roles_path,  class: "btn btn-sm btn-blue pull-left" do %>
         Back
      <% end %>
    </h4>
    <h4 class="col-md-8" align="center">
      Update Role
    </h4>
  </div>
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for @role, url: admin_role_path do |f| %>
          <div class="row mrs mls">
            <%= render 'form', f: f %>
          </div>
          <div class="row">
            <div class="col-md-12" align="center">
              <%= f.submit "Update Role", :class => 'btn btn-default' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/roles/index.html.erb
<div class="container-div">
  <div class="col-xs-12">
    <div class="col-md-1" >
      <h3>
        <%= link_to new_admin_role_path, class: "btn btn-sm btn-green" do %>
          <span class="fa fa-plus" aria-hidden="true"></span> Add Role
        <% end %>
      </h3>
    </div>
    <div class="col-md-10" align="center">
      <h3>User Roles</h3>
    </div>
  </div>

  <div id="message-container" class="row errors"></div>

  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <table class="table table-bordered table-striped table-hover table-data table-overview display">
          <colgroup>
            <col class="col-xs-2">
            <col class="col-xs-2">
            <col class="col-xs-4">
            <col class="col-xs-1">
            <col class="col-xs-3">
          </colgroup>
          <thead>
          <tr>
            <th>Role</th>
            <th>Description</th>
            <th>Permissions</th>
            <th>Admin Only</th>
            <th>Actions</th>
          </tr>
          </thead>
          <tbody>
            <% @roles.each do |role| %>
              <tr>
                <td><%= role.name %></td>
                <td><%= role.description %></td>
                <td>
                  <ul>
                    <% role.permissions.each do |permission| %>
                        <li><%= permission.name %></li>
                    <% end %>
                  </ul>
                </td>
                <td><%= role.admin_only %></td>
                <td class="align-right action-buttons">
                  <%= link_to "Edit", edit_admin_role_path(role), class: 'btn btn-blue btn-sm' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @roles, params: params.to_unsafe_h %>
      </div>
    </div>
  </div>
</div>

app/views/admin/roles/new.html.erb
<div class="container col-md-8 col-md-offset-2">
  <div class="row">
    <h4 class="col-md-2 no-left-pad">
      <%= link_to admin_roles_path,  class: "btn btn-sm btn-blue pull-left" do %>
        Back
      <% end %>
    </h4>
    <h4 class="col-md-8" align="center">
      Add Role
    </h4>
  </div>
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for @role, url: admin_roles_path do |f| %>
          <div class="row mrs mls">
            <%= render 'form', f: f %>
          </div>
          <div class="row">
            <div class="col-md-12" align="center">
              <%= f.submit "Add Role", :class => 'btn btn-default' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>